sudo: required
services: 
  -docker

before_install: 
  - docker build -t gabormol/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gabormol/docker-react npm run test

language: generic